# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python Projects\DedupInterface\MainWindow.ui'
#
# Created: Mon Mar 11 14:53:19 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(771, 392)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 761, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(670, 10, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lbl_file = QtGui.QLabel(self.tab)
        self.lbl_file.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.lbl_file.setObjectName(_fromUtf8("lbl_file"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.txt_file = QtGui.QLineEdit(self.tab)
        self.txt_file.setGeometry(QtCore.QRect(90, 10, 571, 20))
        self.txt_file.setObjectName(_fromUtf8("txt_file"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 681, 271))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.table_summary = QtGui.QTableWidget(self.groupBox)
        self.table_summary.setGeometry(QtCore.QRect(10, 20, 611, 141))
        self.table_summary.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.table_summary.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_summary.setAlternatingRowColors(True)
        self.table_summary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.table_summary.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_summary.setShowGrid(True)
        self.table_summary.setColumnCount(2)
        self.table_summary.setObjectName(_fromUtf8("table_summary"))
        self.table_summary.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_summary.setItem(3, 1, item)
        self.table_summary.verticalHeader().setDefaultSectionSize(28)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Reference Deduplicator", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_file.setText(QtGui.QApplication.translate("MainWindow", "Reference file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Deduplication Summary", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Original Records", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Unique Titles", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Duplicate Titles", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Further Likely Duplicates", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.table_summary.isSortingEnabled()
        self.table_summary.setSortingEnabled(False)
        item = self.table_summary.item(0, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(0, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(1, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(1, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(2, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(2, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(3, 0)
        item.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.table_summary.item(3, 1)
        item.setText(QtGui.QApplication.translate("MainWindow", "\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.table_summary.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

